import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { embeddedTraceRuntime } from '../../shared/embed.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const packageJson = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))
const [hostSource, clientSource, css, traceRuntime] = await Promise.all([
  readFile(resolve(root, 'src/index.js'), 'utf8'),
  readFile(resolve(root, 'src/client.js'), 'utf8'),
  readFile(resolve(root, 'src/client.css'), 'utf8'),
  embeddedTraceRuntime(4),
])

const bundle = `/* Generated by scripts/build.mjs. Source: src/client.js + src/client.css */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(packageJson.name)},
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    const styleId = ${JSON.stringify(packageJson.name)};
    let style = document.querySelector('style[data-plugin="' + styleId + '"]');
    if (style === null) {
      style = document.createElement('style');
      style.dataset.plugin = styleId;
      style.textContent = ${JSON.stringify(css)};
      document.head.appendChild(style);
    }
${traceRuntime}
${clientSource.split('\n').map(line => `    ${line}`).join('\n')}
    return module.exports;
  },
});
`

await mkdir(resolve(root, 'lib'), { recursive: true })
await Promise.all([
  writeFile(resolve(root, 'lib/index.js'), hostSource),
  writeFile(resolve(root, 'lib/client.js'), bundle),
])

console.log(`built ${packageJson.name}: lib/index.js + lib/client.js`)
