import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sources = {
  adapter: 'src/client-ui/runtime/trace-adapter.cjs',
  react: 'src/client-ui/runtime/trace-react.cjs',
  tab: 'src/client-ui/surfaces/tab.cjs',
  overlay: 'src/client-ui/surfaces/overlay.cjs',
}

const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))
const entries = Object.fromEntries(await Promise.all(
  Object.entries(sources).map(async ([name, path]) => [name, await readFile(resolve(root, path), 'utf8')]),
))

function indent(value, spaces) {
  const prefix = ' '.repeat(spaces)
  return value.split('\n').map((line) => `${prefix}${line}`).join('\n')
}

function embeddedCommonJs(name, source) {
  return `    const ${name} = (() => {\n      const module = { exports: {} };\n      const exports = module.exports;\n${indent(source, 6)}\n      return module.exports;\n    })();`
}

const bundle = `/* Generated by scripts/build-client.mjs. Do not edit lib/client.js directly. */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
    const React = require('react');
${embeddedCommonJs('RecaTraceAdapter', entries.adapter)}
${embeddedCommonJs('RecaTrace', entries.react)}
${embeddedCommonJs('RecaTabSurface', entries.tab)}
${embeddedCommonJs('RecaOverlaySurface', entries.overlay)}

    const runtime = Object.freeze({ React, RecaTrace, RecaTraceAdapter });
    exports.name = ${JSON.stringify(pkg.name)};
    exports.inject = ['slots', 'connection', 'sessions'];
    exports.apply = (ctx) => {
      const disposers = [
        RecaTabSurface.registerTab(ctx, runtime),
        RecaOverlaySurface.registerOverlay(ctx, runtime),
      ].filter((dispose) => typeof dispose === 'function');
      return () => disposers.reverse().forEach((dispose) => dispose());
    };
    return module.exports;
  },
});
`

await mkdir(resolve(root, 'lib'), { recursive: true })
await writeFile(resolve(root, 'lib/client.js'), bundle)
console.log(`built ${pkg.name}: one client bundle with tab and overlay surfaces`)
